
export const COUNTRY_CODES = [
    { code: "+1", country: "US/CA", name: "États-Unis/Canada", flag: "🇺🇸" },
    { code: "+7", country: "RU", name: "Russie", flag: "🇷🇺" },
    { code: "+20", country: "EG", name: "Égypte", flag: "🇪🇬" },
    { code: "+27", country: "ZA", name: "Afrique du Sud", flag: "🇿🇦" },
    { code: "+30", country: "GR", name: "Grèce", flag: "🇬🇷" },
    { code: "+31", country: "NL", name: "Pays-Bas", flag: "🇳🇱" },
    { code: "+32", country: "BE", name: "Belgique", flag: "🇧🇪" },
    { code: "+33", country: "FR", name: "France", flag: "🇫🇷" },
    { code: "+34", country: "ES", name: "Espagne", flag: "🇪🇸" },
    { code: "+36", country: "HU", name: "Hongrie", flag: "🇭🇺" },
    { code: "+39", country: "IT", name: "Italie", flag: "🇮🇹" },
    { code: "+40", country: "RO", name: "Roumanie", flag: "🇷🇴" },
    { code: "+41", country: "CH", name: "Suisse", flag: "🇨🇭" },
    { code: "+43", country: "AT", name: "Autriche", flag: "🇦🇹" },
    { code: "+44", country: "UK", name: "Royaume-Uni", flag: "🇬🇧" },
    { code: "+45", country: "DK", name: "Danemark", flag: "🇩🇰" },
    { code: "+46", country: "SE", name: "Suède", flag: "🇸🇪" },
    { code: "+47", country: "NO", name: "Norvège", flag: "🇳🇴" },
    { code: "+48", country: "PL", name: "Pologne", flag: "🇵🇱" },
    { code: "+49", country: "DE", name: "Allemagne", flag: "🇩🇪" },
    { code: "+51", country: "PE", name: "Pérou", flag: "🇵🇪" },
    { code: "+52", country: "MX", name: "Mexique", flag: "🇲🇽" },
    { code: "+53", country: "CU", name: "Cuba", flag: "🇨🇺" },
    { code: "+54", country: "AR", name: "Argentine", flag: "🇦🇷" },
    { code: "+55", country: "BR", name: "Brésil", flag: "🇧🇷" },
    { code: "+56", country: "CL", name: "Chili", flag: "🇨🇱" },
    { code: "+57", country: "CO", name: "Colombie", flag: "🇨🇴" },
    { code: "+58", country: "VE", name: "Venezuela", flag: "🇻🇪" },
    { code: "+60", country: "MY", name: "Malaisie", flag: "🇲🇾" },
    { code: "+61", country: "AU", name: "Australie", flag: "🇦🇺" },
    { code: "+62", country: "ID", name: "Indonésie", flag: "🇮🇩" },
    { code: "+63", country: "PH", name: "Philippines", flag: "🇵🇭" },
    { code: "+64", country: "NZ", name: "Nouvelle-Zélande", flag: "🇳🇿" },
    { code: "+65", country: "SG", name: "Singapour", flag: "🇸🇬" },
    { code: "+66", country: "TH", name: "Thaïlande", flag: "🇹🇭" },
    { code: "+81", country: "JP", name: "Japon", flag: "🇯🇵" },
    { code: "+82", country: "KR", name: "Corée du Sud", flag: "🇰🇷" },
    { code: "+84", country: "VN", name: "Vietnam", flag: "🇻🇳" },
    { code: "+86", country: "CN", name: "Chine", flag: "🇨🇳" },
    { code: "+90", country: "TR", name: "Turquie", flag: "🇹🇷" },
    { code: "+91", country: "IN", name: "Inde", flag: "🇮🇳" },
    { code: "+92", country: "PK", name: "Pakistan", flag: "🇵🇰" },
    { code: "+93", country: "AF", name: "Afghanistan", flag: "🇦🇫" },
    { code: "+94", country: "LK", name: "Sri Lanka", flag: "🇱🇰" },
    { code: "+95", country: "MM", name: "Myanmar", flag: "🇲🇲" },
    { code: "+98", country: "IR", name: "Iran", flag: "🇮🇷" },
    { code: "+212", country: "MA", name: "Maroc", flag: "🇲🇦" },
    { code: "+213", country: "DZ", name: "Algérie", flag: "🇩🇿" },
    { code: "+216", country: "TN", name: "Tunisie", flag: "🇹🇳" },
    { code: "+218", country: "LY", name: "Libye", flag: "🇱🇾" },
    { code: "+220", country: "GM", name: "Gambie", flag: "🇬🇲" },
    { code: "+221", country: "SN", name: "Sénégal", flag: "🇸🇳" },
    { code: "+222", country: "MR", name: "Mauritanie", flag: "🇲🇷" },
    { code: "+223", country: "ML", name: "Mali", flag: "🇲🇱" },
    { code: "+224", country: "GN", name: "Guinée", flag: "🇬🇳" },
    { code: "+225", country: "CI", name: "Côte d'Ivoire", flag: "🇨🇮" },
    { code: "+226", country: "BF", name: "Burkina Faso", flag: "🇧🇫" },
    { code: "+227", country: "NE", name: "Niger", flag: "🇳🇪" },
    { code: "+228", country: "TG", name: "Togo", flag: "🇹🇬" },
    { code: "+229", country: "BJ", name: "Bénin", flag: "🇧🇯" },
    { code: "+230", country: "MU", name: "Maurice", flag: "🇲🇺" },
    { code: "+231", country: "LR", name: "Libéria", flag: "🇱🇷" },
    { code: "+232", country: "SL", name: "Sierra Leone", flag: "🇸🇱" },
    { code: "+233", country: "GH", name: "Ghana", flag: "🇬🇭" },
    { code: "+234", country: "NG", name: "Nigéria", flag: "🇳🇬" },
    { code: "+235", country: "TD", name: "Tchad", flag: "🇹🇩" },
    { code: "+236", country: "CF", name: "Rép. Centrafricaine", flag: "🇨🇫" },
    { code: "+237", country: "CM", name: "Cameroun", flag: "🇨🇲" },
    { code: "+238", country: "CV", name: "Cap-Vert", flag: "🇨🇻" },
    { code: "+239", country: "ST", name: "São Tomé", flag: "🇸🇹" },
    { code: "+240", country: "GQ", name: "Guinée équatoriale", flag: "🇬🇶" },
    { code: "+241", country: "GA", name: "Gabon", flag: "🇬🇦" },
    { code: "+242", country: "CG", name: "Congo", flag: "🇨🇬" },
    { code: "+243", country: "CD", name: "RD Congo", flag: "🇨🇩" },
    { code: "+244", country: "AO", name: "Angola", flag: "🇦🇴" },
    { code: "+245", country: "GW", name: "Guinée-Bissau", flag: "🇬🇼" },
    { code: "+246", country: "IO", name: "Diego Garcia", flag: "🇮🇴" },
    { code: "+248", country: "SC", name: "Seychelles", flag: "🇸🇨" },
    { code: "+249", country: "SD", name: "Soudan", flag: "🇸🇩" },
    { code: "+250", country: "RW", name: "Rwanda", flag: "🇷🇼" },
    { code: "+251", country: "ET", name: "Éthiopie", flag: "🇪🇹" },
    { code: "+252", country: "SO", name: "Somalie", flag: "🇸🇴" },
    { code: "+253", country: "DJ", name: "Djibouti", flag: "🇩🇯" },
    { code: "+254", country: "KE", name: "Kenya", flag: "🇰🇪" },
    { code: "+255", country: "TZ", name: "Tanzanie", flag: "🇹🇿" },
    { code: "+256", country: "UG", name: "Ouganda", flag: "🇺🇬" },
    { code: "+257", country: "BI", name: "Burundi", flag: "🇧🇮" },
    { code: "+258", country: "MZ", name: "Mozambique", flag: "🇲🇿" },
    { code: "+260", country: "ZM", name: "Zambie", flag: "🇿🇲" },
    { code: "+261", country: "MG", name: "Madagascar", flag: "🇲🇬" },
    { code: "+262", country: "RE", name: "Réunion/Mayotte", flag: "🇷🇪" },
    { code: "+263", country: "ZW", name: "Zimbabwe", flag: "🇿🇼" },
    { code: "+264", country: "NA", name: "Namibie", flag: "🇳🇦" },
    { code: "+265", country: "MW", name: "Malawi", flag: "🇲🇼" },
    { code: "+266", country: "LS", name: "Lesotho", flag: "🇱🇸" },
    { code: "+267", country: "BW", name: "Botswana", flag: "🇧🇼" },
    { code: "+268", country: "SZ", name: "Eswatini", flag: "🇸🇿" },
    { code: "+269", country: "KM", name: "Comores", flag: "🇰🇲" },
    { code: "+290", country: "SH", name: "Sainte-Hélène", flag: "🇸🇭" },
    { code: "+291", country: "ER", name: "Érythrée", flag: "🇪🇷" },
    { code: "+297", country: "AW", name: "Aruba", flag: "🇦🇼" },
    { code: "+298", country: "FO", name: "Îles Féroé", flag: "🇫🇴" },
    { code: "+299", country: "GL", name: "Groenland", flag: "🇬🇱" },
    { code: "+350", country: "GI", name: "Gibraltar", flag: "🇬🇮" },
    { code: "+351", country: "PT", name: "Portugal", flag: "🇵🇹" },
    { code: "+352", country: "LU", name: "Luxembourg", flag: "🇱🇺" },
    { code: "+353", country: "IE", name: "Irlande", flag: "🇮🇪" },
    { code: "+354", country: "IS", name: "Islande", flag: "🇮🇸" },
    { code: "+355", country: "AL", name: "Albanie", flag: "🇦🇱" },
    { code: "+356", country: "MT", name: "Malte", flag: "🇲🇹" },
    { code: "+357", country: "CY", name: "Chypre", flag: "🇨🇾" },
    { code: "+358", country: "FI", name: "Finlande", flag: "🇫🇮" },
    { code: "+359", country: "BG", name: "Bulgarie", flag: "🇧🇬" },
    { code: "+370", country: "LT", name: "Lituanie", flag: "🇱🇹" },
    { code: "+371", country: "LV", name: "Lettonie", flag: "🇱🇻" },
    { code: "+372", country: "EE", name: "Estonie", flag: "🇪🇪" },
    { code: "+373", country: "MD", name: "Moldavie", flag: "🇲🇩" },
    { code: "+374", country: "AM", name: "Arménie", flag: "🇦🇲" },
    { code: "+375", country: "BY", name: "Biélorussie", flag: "🇧🇾" },
    { code: "+376", country: "AD", name: "Andorre", flag: "🇦🇩" },
    { code: "+377", country: "MC", name: "Monaco", flag: "🇲🇨" },
    { code: "+378", country: "SM", name: "Saint-Marin", flag: "🇸🇲" },
    { code: "+380", country: "UA", name: "Ukraine", flag: "🇺🇦" },
    { code: "+381", country: "RS", name: "Serbie", flag: "🇷🇸" },
    { code: "+382", country: "ME", name: "Monténégro", flag: "🇲🇪" },
    { code: "+383", country: "XK", name: "Kosovo", flag: "🇽🇰" },
    { code: "+385", country: "HR", name: "Croatie", flag: "🇭🇷" },
    { code: "+386", country: "SI", name: "Slovénie", flag: "🇸🇮" },
    { code: "+387", country: "BA", name: "Bosnie", flag: "🇧🇦" },
    { code: "+389", country: "MK", name: "Macédoine du Nord", flag: "🇲🇰" },
    { code: "+420", country: "CZ", name: "Tchéquie", flag: "🇨🇿" },
    { code: "+421", country: "SK", name: "Slovaquie", flag: "🇸🇰" },
    { code: "+423", country: "LI", name: "Liechtenstein", flag: "🇱🇮" },
    { code: "+500", country: "FK", name: "Îles Malouines", flag: "🇫🇰" },
    { code: "+501", country: "BZ", name: "Belize", flag: "🇧🇿" },
    { code: "+502", country: "GT", name: "Guatemala", flag: "🇬🇹" },
    { code: "+503", country: "SV", name: "Salvador", flag: "🇸🇻" },
    { code: "+504", country: "HN", name: "Honduras", flag: "🇭🇳" },
    { code: "+505", country: "NI", name: "Nicaragua", flag: "🇳🇮" },
    { code: "+506", country: "CR", name: "Costa Rica", flag: "🇨🇷" },
    { code: "+507", country: "PA", name: "Panama", flag: "🇵🇦" },
    { code: "+508", country: "PM", name: "St-Pierre-et-Miquelon", flag: "🇵🇲" },
    { code: "+509", country: "HT", name: "Haïti", flag: "🇭🇹" },
    { code: "+590", country: "GP", name: "Guadeloupe", flag: "🇬🇵" },
    { code: "+591", country: "BO", name: "Bolivie", flag: "🇧🇴" },
    { code: "+592", country: "GY", name: "Guyana", flag: "🇬🇾" },
    { code: "+593", country: "EC", name: "Équateur", flag: "🇪🇨" },
    { code: "+594", country: "GF", name: "Guyane française", flag: "🇬🇫" },
    { code: "+595", country: "PY", name: "Paraguay", flag: "🇵🇾" },
    { code: "+596", country: "MQ", name: "Martinique", flag: "🇲🇶" },
    { code: "+597", country: "SR", name: "Suriname", flag: "🇸🇷" },
    { code: "+598", country: "UY", name: "Uruguay", flag: "🇺🇾" },
    { code: "+599", country: "CW", name: "Curaçao", flag: "🇨🇼" },
    { code: "+670", country: "TL", name: "Timor-Leste", flag: "🇹🇱" },
    { code: "+672", country: "AQ", name: "Antarctique", flag: "🇦🇶" },
    { code: "+673", country: "BN", name: "Brunei", flag: "🇧🇳" },
    { code: "+674", country: "NR", name: "Nauru", flag: "🇳🇷" },
    { code: "+675", country: "PG", name: "Papouasie-Nouvelle-Guinée", flag: "🇵🇬" },
    { code: "+676", country: "TO", name: "Tonga", flag: "🇹🇴" },
    { code: "+677", country: "SB", name: "Îles Salomon", flag: "🇸🇧" },
    { code: "+678", country: "VU", name: "Vanuatu", flag: "🇻🇺" },
    { code: "+679", country: "FJ", name: "Fidji", flag: "🇫🇯" },
    { code: "+680", country: "PW", name: "Palaos", flag: "🇵🇼" },
    { code: "+681", country: "WF", name: "Wallis-et-Futuna", flag: "🇼🇫" },
    { code: "+682", country: "CK", name: "Îles Cook", flag: "🇨🇰" },
    { code: "+683", country: "NU", name: "Niue", flag: "🇳🇺" },
    { code: "+685", country: "WS", name: "Samoa", flag: "🇼🇸" },
    { code: "+686", country: "KI", name: "Kiribati", flag: "🇰🇮" },
    { code: "+687", country: "NC", name: "Nouvelle-Calédonie", flag: "🇳🇨" },
    { code: "+688", country: "TV", name: "Tuvalu", flag: "🇹🇻" },
    { code: "+689", country: "PF", name: "Polynésie française", flag: "🇵🇫" },
    { code: "+690", country: "TK", name: "Tokelau", flag: "🇹🇰" },
    { code: "+691", country: "FM", name: "Micronésie", flag: "🇫🇲" },
    { code: "+692", country: "MH", name: "Îles Marshall", flag: "🇲🇭" },
    { code: "+850", country: "KP", name: "Corée du Nord", flag: "🇰🇵" },
    { code: "+852", country: "HK", name: "Hong Kong", flag: "🇭🇰" },
    { code: "+853", country: "MO", name: "Macao", flag: "🇲🇴" },
    { code: "+855", country: "KH", name: "Cambodge", flag: "🇰🇭" },
    { code: "+856", country: "LA", name: "Laos", flag: "🇱🇦" },
    { code: "+880", country: "BD", name: "Bangladesh", flag: "🇧🇩" },
    { code: "+886", country: "TW", name: "Taïwan", flag: "🇹🇼" },
    { code: "+960", country: "MV", name: "Maldives", flag: "🇲🇻" },
    { code: "+961", country: "LB", name: "Liban", flag: "🇱🇧" },
    { code: "+962", country: "JO", name: "Jordanie", flag: "🇯🇴" },
    { code: "+963", country: "SY", name: "Syrie", flag: "🇸🇾" },
    { code: "+964", country: "IQ", name: "Irak", flag: "🇮🇶" },
    { code: "+965", country: "KW", name: "Koweït", flag: "🇰🇼" },
    { code: "+966", country: "SA", name: "Arabie saoudite", flag: "🇸🇦" },
    { code: "+967", country: "YE", name: "Yémen", flag: "🇾🇪" },
    { code: "+968", country: "OM", name: "Oman", flag: "🇴🇲" },
    { code: "+970", country: "PS", name: "Palestine", flag: "🇵🇸" },
    { code: "+971", country: "AE", name: "Émirats arabes unis", flag: "🇦🇪" },
    { code: "+972", country: "IL", name: "Israël", flag: "🇮🇱" },
    { code: "+973", country: "BH", name: "Bahreïn", flag: "🇧🇭" },
    { code: "+974", country: "QA", name: "Qatar", flag: "🇶🇦" },
    { code: "+975", country: "BT", name: "Bhoutan", flag: "🇧🇹" },
    { code: "+976", country: "MN", name: "Mongolie", flag: "🇲🇳" },
    { code: "+977", country: "NP", name: "Népal", flag: "🇳🇵" },
    { code: "+992", country: "TJ", name: "Tadjikistan", flag: "🇹🇯" },
    { code: "+993", country: "TM", name: "Turkménistan", flag: "🇹🇲" },
    { code: "+994", country: "AZ", name: "Azerbaïdjan", flag: "🇦🇿" },
    { code: "+995", country: "GE", name: "Géorgie", flag: "🇬🇪" },
    { code: "+996", country: "KG", name: "Kirghizistan", flag: "🇰🇬" },
    { code: "+998", country: "UZ", name: "Ouzbékistan", flag: "🇺🇿" },
  ];